server:
  port: 9090

spring:
  application:
    name: BlogStackQNAHubService

  datasource:
    url: jdbc:postgresql://ec2-3-84-24-210.compute-1.amazonaws.com:5432/BlogStackMaster
    #url: jdbc:postgresql://localhost:5433/BlogStackMaster
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

qnahub-service-version: v1.0
