server:
  port: 9090

spring:
  application:
    name: BlogStackQNAHubService

  datasource:
#    url: jdbc:postgresql://ec2-3-110-224-124.ap-south-1.compute.amazonaws.com:5432/blogstackmaster
    url: jdbc:postgresql://localhost:5432/BlogStackMaster
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

qnahub-service-version: v1.0
